print("""Twinkle Twinkle Little Star. Claudia Jones. PREVIEW. ...
The Wheels on the Bus. Claudia Jones. PREVIEW. ...
Old MacDonald Had a Farm. Claudia Jones. ...
Itsy Bitsy Spider. Julie Ellis. ...
Hickory Dickory Dock. Julie Ellis. ...
Finger Family. Stephen Smith. ...
Row Row Row Your Boat. Julie Ellis. ...
Five Little Monkeys. Claudia Jones.""")

