d = {}
name = input("enter name = ")
language = input("enter a language =")
d.update({name: language})
name = input("enter name =")
language = input("enter a language =")
d.update({name: language})
name = input("enter name =")
language = input("enter a language =")
d.update({name: language})
name = input("enter name =")
language = input("enter a language =")
d.update({name: language})
print(d)
             
