s = set()
a = int(input("enter a number ="))
s.add(a)
a = int(input("enter a number ="))
s.add(a)
a = int(input("enter a number ="))
s.add(a)
a = int(input("enter a number ="))
s.add(a)
a = int(input("enter a number ="))
s.add(a)
a = int(input("enter a number ="))
s.add(a)
a = int(input("enter a number ="))
s.add(a)
print(s)
print(type(s))
